export const IMAGES = {
    SplashLogo: require('./images/splashLogo.png'),
    SplashBG: require('./images/splashBG.png'),
    BackIcon: require('./images/backIcon.png'),
    ProfileIcon: require('./images/profileIcon.png'),
    SettingsIcon: require('./images/settingsIcon.png'),
    EditProfileIcon: require('./images/editProfileIcon.png'),
    RightArrowIcon: require('./images/rightArrowIcon.png'),
    UploadIcon: require('./images/uploadIcon.png'),
    GrayBgIcon: require('./images/grayBgIcon.png'),
    GraphIcon: require('./images/graphIcon.png'),
    GraphVerticalIcon: require('./images/graph_vertical.png'),
    TomatoIcon: require('./images/tomato.png'),
    PlusIcon: require('./images/plusIcon.png'),
    DeleteIcon: require('./images/delete.png'),
    EditIcon: require('./images/editIcon.png'),
    CalendarIcon: require('./images/calendar.png'),
    RefreshIcon: require('./images/refreshIcon.png'),
    NoGroupDataIcon: require('./images/no_group_farm_image.png'),
    NoReportsDataIcon: require('./images/no_reports_data_image.png'),
}

export const COLORS = {
    background_color: '#F8F8F8',
    black_400: '#333333',
    white: '#ffffff',
    ButtonBg: '#361500',
    black: '#000000',
    black_300: '#545454',
    inputBg: '#EBE8E6',
    black_200: '#8A8A8A',
    textColor: '#606060',
    subTextColor: '#9C9C9C',
    borderColor: '#DEDEDE',
    brown_200: '#A3938A',
    brown_400: '#5E4433',
    brown_300: '#786254',
    brown_500: '#361500',
    black_50: '#E6E6E6',
    black_100: '#B0B0B0',
    groupListItemBg: '#E6E6E64D',
    homeNoDataBg: '#D9D9D936',
}
